version: '3.8'

services:
  laravel-app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./back:/var/www
    command: >
      bash -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev zip unzip git 
      libonig-dev libxml2-dev && docker-php-ext-install pdo pdo_mysql gd
      && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer 
      && composer install 
      && php artisan key:generate
      && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db

  nuxt-app:
    image: node:16
    container_name: nuxt
    working_dir: /app
    volumes:
      - ./front:/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql_db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
