name: Deploy Nuxt.js and Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa $SERVER_HOST >> ~/.ssh/known_hosts
        
    - name: Clone repository
      run: git clone git@$SERVER_HOST:your_username/your_repository.git app
      
    - name: Navigate to Laravel directory
      run: cd app/laravel
      
    - name: Install Laravel dependencies
      run: composer install
      
    - name: Set Laravel environment
      run: cp .env.example .env && php artisan key:generate && php artisan config:cache
      
    - name: Navigate to Nuxt.js directory
      run: cd ../nuxt
      
    - name: Install Nuxt.js dependencies
      run: npm install
      
    - name: Build Nuxt.js project
      run: npm run build
      
    - name: Deploy to server
      run: |
        rsync -avz --delete --exclude=node_modules --exclude=.git ../nuxt/ $SERVER_ENV@$SERVER_HOST:/path/to/your/nuxt/directory
        rsync -avz --delete --exclude=vendor --exclude=.git ../laravel/ $SERVER_ENV@$SERVER_HOST:/path/to/your/laravel/directory
